// Este archivo se mantiene ejecutando scripts/refresh-training.py script

= Red Hat Application Development I: Programming in Java EE (AD183)

[.big]#*Descripción del curso*#

*Conozca la forma en que los desarrolladores de Java SE escriben las aplicaciones Java EE.*

Red Hat Application Development I: Programming in Java EE (AD183) permite que los desarrolladores experimentados de Java Standard Edition (Java SE) accedan al mundo de Java Enterprise Edition (Java EE).

Este curso se basa en Red Hat Enterprise Application Platform 7.0.

Aprenderá sobre las distintas especificaciones que conforman Java EE. Mediante laboratorios prácticos, transformará una aplicación Java SE sencilla de la línea de comandos en una aplicación empresarial de varios niveles usando distintas especificaciones Java EE, incluidos Enterprise Java Beans, la API de Java Persistence, el servicio de mensajería de Java, JAX-RS para servicios REST, contextos e inyección de dependencia (CDI) y JAAS para asegurar la aplicación.

Una vez que haya completado el curso, recibirá acceso extendido a laboratorios prácticos durante 45 días para todo curso que incluya un entorno virtual.

*Nota:* El curso se ofrece como clase virtual de cinco días o en la modalidad autorregulado. Los tiempos pueden variar conforme lo realice. Para conocer toda la información del curso, el cronograma y los precios, seleccione su ubicación y, luego, el botón "Explorar ahora" en el menú de la derecha.

[.big]#*Resumen del curso*#

* Generación de aplicaciones Java EE de varios niveles
* Empaquetado e implementación de aplicaciones Java EE
* Creación de Enterprise Java Beans, incluidos beans dirigidos por mensaje
* Gestión de la persistencia
* Creación de servicios REST con JAX-RS
* Implementación de contextos e inyección de dependencia
* Creación de aplicaciones de mensajería con JMS
* Protección de las aplicaciones Java EE con JAAS

[.big]#*Público destinatario del curso*#

El curso está diseñado para los desarrolladores de Java que deseen aprender más sobre las especificaciones del mundo de Java Enterprise Edition (Java EE).

[.big]#*Requisitos previos para el curso*#

* Debe dominar el desarrollo de aplicaciones Java SE (es requisito contar con más de dos años de experiencia).
* Debe dominar el uso de entornos de desarrollo integrado (IDE), como Red Hat Developer Studio o Eclipse.
* Se aconseja contar con experiencia con Maven, aunque no es obligatorio.

Para más detalles, o para inscribirse:
https://www.redhat.com/es/services/training/ad183-red-hat-application-development-i-programming-java-ee
