// Este archivo se mantiene ejecutando scripts/refresh-training.py script

= Developing Rules Applications with Red Hat JBoss BRMS (JB463)

[.big]#*Descripción del curso*#

:: 
 
Visión general de Red Hat JBoss BRMS:: 
Conozca la arquitectura y los requisitos empresariales de Red Hat JBoss Business Rules Management System (BRMS).
Creación de reglas básicas:: 
Cree reglas comerciales básicas con Red Hat JBoss Developer Studio (JBDS).
Integración de reglas comerciales en aplicaciones Java:: 
Aprenda a integrar el procesamiento de reglas en una aplicación con una API.
Tablas de decisión:: 
Conozca el propósito y el diseño de una tabla de decisión de hoja de cálculo y descubra cómo JBoss BRMS carga la tabla de decisión en tiempo de ejecución.
Lenguajes específicos de dominio:: 
Conozca el propósito de los lenguajes específicos de dominio (DSL), descubra cómo declararlos y cómo utilizarlos en una regla.
Pruebas de reglas:: 
Aprenda sobre la prueba JUnit y cómo evaluar una aplicación BRMS. 
Creación de reglas complejas:: 
Aprenda a usar características complejas del motor de reglas BRMS.
Ejecución de reglas de control:: 
Aprenda a implantar estrategias de resolución de conflictos en la ejecución de reglas.
Depuración de Drools:: 
Aprenda a depurar aplicaciones Drools en Red Hat JBoss Developer Studio.
Procesamiento de eventos complejos:: 
Utilice el procesamiento complejo de eventos con reglas.

*Nota:* El resumen del curso está sujeto a cambios en función del avance de la tecnología y a medida que evolucione la naturaleza de las tareas relacionadas. Si tiene alguna pregunta o necesita confirmación sobre cierto objetivo o tema concreto, comuníquese con un https://www.redhat.com/es/services/training-and-certification/contact-us[especialista en capacitación].

Para más detalles, o para inscribirse:
https://www.redhat.com/es/services/training/jb463-developing-rules-applications-red-hat-jboss-brms
